### ISSUE TITLE
Contributions not imported

### ISSUE THREAD

**Issue by danielnmai** [miromannino/Contributions-Importer-For-Github#1]
I downloaded the package, and wrote a script. The script seems to run fine, I can see the analysing, commit and apply changes logs, but no contribution history is updated on my profile.

```
# run_script.py 
import git
from git_contributions_importer import *

# private repo
repo = git.Repo("../../infuse/clover-dashboard-react")
# mock repo
mock_repo = git.Repo("../../daniel/mock-repo")

importer = Importer([repo], mock_repo)
importer.set_author(['danielmai1728@gmail.com', 'daniel@infuse.us'])
  
importer.import_repository()
```

Could it be I missed some setup steps?

**Comment by julia320** [comment]
@danielnmai was this ever solved? I'm having the same issue

**Comment by danielnmai** [comment]
@julia320 I managed to solve the issue. I don't remember what the exact steps I took, but if you can see the script run and complete, remember to go into your mock folder and push up the changes to Github!
