### ISSUE TITLE
Commits not reflected in GitHub

### ISSUE THREAD

**Issue by julia320** [miromannino/Contributions-Importer-For-Github#11]
I ran the script provided in the documentation and it seemed to have the expected behavior - it analyzed all the commits and ignored those not done by me. However, I did not see the commits reflected on my profile after the script was complete. It is entirely possible that I've missed a step somewhere, so if you have any guidance it would be appreciated!

**Comment by miromannino** [comment]
Yes I'll try to be more clear in the documentation! Basically the code creates commit but it is up to you to push them (because also it depends on you how you want to do it, credentials, etc)

**Comment by gward35** [comment]
@julia320 did you ever get this working I'm having the same issue and opened a new issue on it

**Comment by julia320** [comment]
@gward35 yes, after I went in to my other repo and pushed the commits, they showed up in my commit chart on my page. I looked at the issue you opened and unfortunately I'm not familiar enough with the code to help, but good luck!
