### ISSUE TITLE
Contributions from enterprise to github

### ISSUE THREAD

**Issue by razanjoshi** [miromannino/Contributions-Importer-For-Github#12]
Can we import Github Enterprise private repo's contribution to Github mock repo?

**Comment by miromannino** [comment]
Yes, you can import from any git repository, even if it's private on your computer without being even hosted somewhere.

**Comment by razanjoshi** [comment]
Running the script, i pushed 200+ commits up to the mock repo but the contribution chart has not changed a bit. Anyone know the reason?

<img width="1037" alt="Screenshot 2019-07-09 at 16 53 56" src="https://user-images.githubusercontent.com/4223130/60903974-2efbd580-a26a-11e9-98e3-38342313cd9a.png">
<img width="327" alt="Screenshot 2019-07-09 at 16 55 07" src="https://user-images.githubusercontent.com/4223130/60904062-5357b200-a26a-11e9-9e96-8355a676735d.png">

**Comment by razanjoshi** [comment]
@miromannino Made a blog post on how to use this. Please have a look at your free time.
https://medium.com/@razan.joc/how-i-restored-my-git-contributions-7ddb27f06d4e

**Comment by miromannino** [comment]
That is very good thank you! I'll include this article as link in the readme.txt so it can be useful for others.

**Comment by YourMobileGeek** [comment]
@miromannino Thank you for building this! I'm having a bit of trouble setting this up on my end and was wondering if this is something you can possibly take a look at? Thanks!

**Comment by razanjoshi** [comment]
@YourMobileGeek Can you share what was the problem that you were facing?

**Comment by YourMobileGeek** [comment]
@razanjoshi Yes of course! Even though the article was very helpful I realized there was a bit of confusion where it mentions putting your Git Repo & Mock Repo in the script file. I was actually putting the URL's of both of the repo's instead of putting where the file is hosted on my computer.

**Comment by razanjoshi** [comment]
Ya glad that you made it work. I tried to write down as clear as I can, learning from all the confusions I had in the beginning. Thanks for bringing that up, I will try to edit that part to make it less confusing. @YourMobileGeek 🥇

**Comment by YourMobileGeek** [comment]
@razanjoshi Completely understandable, thanks for taking the time to write the blog too. I've been trying to find something like this for the past two years. The only thing that's odd is when I run the script, the commits are going to my mock repo, but aren't showing as contributions on the actual Contribution Chart.

Here's the link to the repo: https://github.com/YourMobileGeek/mock-repo-bitbucket
