### ISSUE TITLE
Error when running script

### ISSUE THREAD

**Issue by YourMobileGeek** [miromannino/Contributions-Importer-For-Github#14]
<img width="1190" alt="Screen Shot 2019-08-23 at 2 30 22 PM" src="https://user-images.githubusercontent.com/8063614/63624836-9b305f80-c5b2-11e9-9e73-9b0b6be046b0.png">

I followed the instructions listed in GitHub, and currently receiving this odd " NoSuchPathError " , any help would be appreciated.

**Comment by miromannino** [comment]
Hello @YourMobileGeek it seems like you are trying to analyse a repository that is not saved in your computer. This is a feature that is currently not supported by the script. You can simply clone your bitbucket repo in your computer in order to do it.
