### ISSUE TITLE
Is there a way to keep original commit messages?

### ISSUE THREAD

**Issue by guiquintelas** [miromannino/Contributions-Importer-For-Github#15]
If there isn't I would love to implement this in my free time

Been using this tool for quite some time now, it's awesome

And thanks for this repo :D

**Comment by miromannino** [comment]
Feel free to implement :)
It's going to be very easy to do. Thank you!

**Comment by LucaPipolo** [comment]
@guiquintelas, @miromannino No news on this? Would be great to have this feature. 🙏🏼
