### ISSUE TITLE
Language is java instead of kotlin

### ISSUE THREAD

**Issue by hikikomoriphoenix** [miromannino/Contributions-Importer-For-Github#16]
My project is an android app written in kotlin but my mock repo shows its 100% java. How to make it reflect the correct language?

**Comment by Aizen741** [comment]
Okay First Make a new File with name ".gitattributes" in your repo and after that, in the .gitattributes file, Type the following: 

*.kotlin linguist-detectable=true
 *.java linguist-detectable=false
 *.xml linguist-detectable=false

![Screenshot from 2019-12-12 06-01-45](https://user-images.githubusercontent.com/39067962/70672554-a0223780-1ca5-11ea-82f2-eea8aa96ead1.png)

![Screenshot from 2019-12-12 06-01-52](https://user-images.githubusercontent.com/39067962/70672558-a44e5500-1ca5-11ea-826a-224983f29c86.png)

**Comment by hikikomoriphoenix** [comment]
The file generated from this project and pushed into my mock repo is java. Therefore it is not a case of github misreporting the language. It looks like this project does not support kotlin and defaults to java.
