### ISSUE TITLE
Contributions not being shown on Github

### ISSUE THREAD

**Issue by gward35** [miromannino/Contributions-Importer-For-Github#17]
Hi, I have seen the two closed issues on this topic and am hoping to understand why the contributions dont show up. 

In my script I have 

```
repo = git.Repo("../../Projects/otter")
# Your mock repo
mock_repo = git.Repo("../../Projects/mock-repo-otter")
importer = Importer([repo], mock_repo)
```

I run the script and see my commits being analyzed with others not by me skipped

I cd to the mock repo and run ```git push```

In my mock repo I see latest activity "...seconds ago" 

But the commits arent reflected in the contribution chart. 

Why is this ?

**Comment by miromannino** [comment]
Hello @gward35,
did you try to go to your GitHub clicking Update Contributions in the setting page?
Commits might not show up immediately, or they don't show up at all if there are more than one year old.

**Comment by bachng248** [comment]
Hi. I'm having the same issue. @miromannino I have tried clicking Update Contributions but contribution chart remains unchanged. Most commits in mock repo are recently. Thanks.

**Comment by gward35** [comment]
@miromannino , just tried that with no change in my contribution graph, my commits were recent (in the last two weeks). 

One question I wanted to ask was about the setAuthor() method. I trying to map private bitbucket
contributions from my work to show up in this mock repo with my personal email. Should the emails be in a specific order? right now I'm passing in my work email first and my personal email second.

**Comment by gward35** [comment]
@miromannino @bachng248  I didn't have my work email registered in my github settings (facepalm). The commits are showing up now. If you are using a work email with bitbucket, gitlab, etc make sure you add it and verify it in your github profile! You can close this ticket.
