### ISSUE TITLE
Imports commits of others too

### ISSUE THREAD

**Issue by Akhilez** [miromannino/Contributions-Importer-For-Github#18]
When I import commits from bitbucket to github, I get way too many commits.
It is importing all the commits regardless of who is commiting.
My commits include a merge commit from others. I'm guessing that is the problem because it is not importing commits out of the merged ones.

I expected it to import commits which had my email id only. Apparently, my github calendar has a few "fake" commits (commits that are not actually mine) which is not the intended purpose of this project.

**Comment by YourMobileGeek** [comment]
@Akhilez A few of my imported commits come from BitBucket as well. I have my `run_script.py` file set up to import the commits I've done from the last time I ran the python script, which helps prevents importing the same commits, merged commits and imported commits that aren't originally from me. 

One thing that I realized helped, is making sure the emails I include in the `importer.set_author` are also emails that are included in my Github email settings so it knows which emails to count as commits.

**Comment by miromannino** [comment]
Hello! yes surely you need to do the `set_author`.

Despite that once Github add new contributions (that include also your coworkers) you can't remove unless you delete the mock repo.

So my suggestion is to delete the mock repository on github and to start all over the contribution importing with `set_author`.

Let me know if it worked!

**Comment by Akhilez** [comment]
I did set the author to a list of 2 emails. One of them is set as the git's global user.email. So, I'm not sure what is wrong in my case.
One possible fix might be setting author with a single email. I'll try that soon and update here.

This is the original code with changed values:

`
import git
from git_contributions_importer import *

# -------------------- VALUES ------------------------

bit_bucket_repos = [
    "../test",
    "../workrepo"
]

mock_repo = '.'

personal_email = 'email1@gmail.com'
work_email = 'email2@work.com'

# ----------------------------------------------------

bit_bucket_repos = [git.Repo(repo) for repo in bit_bucket_repos]
mock_repo = git.Repo(mock_repo)

importer = Importer(bit_bucket_repos, mock_repo)
importer.set_author([personal_email, work_email])

importer.import_repository()
`
