### ISSUE TITLE
Each run creates duplicates

### ISSUE THREAD

**Issue by iamface** [miromannino/Contributions-Importer-For-Github#19]
Hello,

Is there a way to prevent duplicate commits through defining a start date?

I ran this initially and everything worked great, but after a couple more days of development, I re-ran the script so it could show the latest few day's commits, but I noticed it also pulled the previous commits again, so the contributions show more commits than intended.

**Comment by YourMobileGeek** [comment]
Hello, 

One way I was able to prevent duplicate commits was by setting the **Just Last Commit** parameter `importer.set_start_from_last(false)` which basically the importer will fetch the last commited date from mock_repo and will ignore all commits before this date.

Hope this helps.

**Comment by iamface** [comment]
Somehow I missed those options.. This was very helpful thank you!

**Comment by YourMobileGeek** [comment]
@iamface glad you were able to figure it out!
