### ISSUE TITLE
unable to import 'git' pylint (import-error) 

### ISSUE THREAD

**Issue by YourMobileGeek** [miromannino/Contributions-Importer-For-Github#22]
<img width="322" alt="Screen Shot 2020-12-11 at 11 38 30 AM" src="https://user-images.githubusercontent.com/8063614/101932223-7ba6b700-3ba8-11eb-8170-5808ba7c6137.png">

<img width="304" alt="Screen Shot 2020-12-11 at 11 38 13 AM" src="https://user-images.githubusercontent.com/8063614/101932225-7c3f4d80-3ba8-11eb-84f2-23975e1db911.png">

I'm getting this weird _**unable to import 'git'**_ error, I tried troubleshooting on my end but no luck. Was hoping someone may know a quick fix to this.

**Comment by LucaPipolo** [comment]
Hey @YourMobileGeek ,

I solved this by installing the `gitpython` Phyton module.
Just running `pip3 install gitpython` should do the trick.

Hope it helps!

**Comment by YourMobileGeek** [comment]
<img width="670" alt="Screen Shot 2021-01-03 at 12 14 12 PM" src="https://user-
images.githubusercontent.com/8063614/103484551-aeb22400-4dbd-11eb-8946-b3d632546a94.png">

@LucaPipolo hello, thanks for the input! That was my first go-to thought but kept running into this weird warning message that I never ran into before. Been troubleshooting for a while but haven't had any luck.

**Comment by LucaPipolo** [comment]
Hm… looking at the warning you posted seems that there is a permissions issue there. Perhaps related to the way you installed Python on your machine? 🤔 

Did you try to install gitpython with sudo: `sudo pip3 install gitpython`?

**Comment by YourMobileGeek** [comment]
That was my second step with installation, but displayed the same message as above even after using `sudo` command. Not sure if this has to deal with Python 2.7 no longer being supported, even though I have Python 3.9

<img width="667" alt="Screen Shot 2021-01-04 at 9 29 20 AM" src="https://user-images.githubusercontent.com/8063614/103545377-7834e180-4e6f-11eb-931a-70fe22841f99.png">

**Comment by GavMan1995** [comment]
Did you ever figure this out? I'm getting the same issue.

**Comment by YourMobileGeek** [comment]
@GavMan1995 I'm a few days late but unfortunately no 😔, was there any luck on your end by chance? I'm thinking the main factor could be the python 2.7 no longer being supported but that's the default library that Apple references for their MacBook's

**Comment by GavMan1995** [comment]
@YourMobileGeek Nope unfortunately still nothing. I'll be taking some time later this week to see if I can figure it out. I'll let you guys know if I can figure it out.

**Comment by nilooy5** [comment]
finally, I've found a solution. Open the whole repo as a pycharm project then run the script from the left side menu using right-mouse click. It will hopefully work since it worked for me. I know it's not a savvy solution but I'm just so happy that it worked.

**Comment by YourMobileGeek** [comment]
@nilooy5 Glad you were able to find a solution! When mentioning running this as a pycharm project are you able to provide a breakdown on how you were able to do this? I've never used pycharm like that before. 😅

**Comment by YourMobileGeek** [comment]
@GavMan1995 @nilooy5 I was able to find sometime today to sync with a friend of mine whose a python wizard and was able to come up with two separate solutions. One of them you can simply add` # import sys` &` sys.path.append ("/usr/local/lib/python3.9/site-packages")` within your python script file before the `import git`. 

Another solution would be creating your own python virtual environment, he had me use [Pipenv](https://pipenv.pypa.io/en/latest/) which you can simply install using `pip3 install pipenv `. If needing some more assistance I'm more than happy to jump on a Google Hangouts call and help you resolve this issue. My best contact email " arianadavis62@gmail.com ". Hope this helps! :)

**Comment by nilooy5** [comment]
@YourMobileGeek glad you're able to find a solution. Sorry I didn't notice your precious comment where you asked for a guided solution.

**Comment by YourMobileGeek** [comment]
@nilooy5 you're good, I ended up figuring it out the pycharm way but that still wasn't able to fix the bug I was running into. 😕 .. I appreciate the help overall though!

**Comment by Ryukyo** [comment]
For me, `pip3 install GitPython 3` did the trick
