### ISSUE TITLE
importer.set_start_from_last should exclude last commit

### ISSUE THREAD

**Issue by lk77** [miromannino/Contributions-Importer-For-Github#25]
Hello,

when using `importer.set_start_from_last(True)`,
only commits before the date are ignored
but if the dates are equals it should be ignored too and it's not the case,
this cause the last commit to be repeated twice

```
commit 07072356f7ddc123e46e8ee9c3c622ff976c00c5 (HEAD -> master)
Date:   Thu Jun 3 13:27:36 2021 +0000

commit 59b18244053533fc1510df6d5e33ad51f06bf551 (origin/master, origin/HEAD)
Date:   Thu Jun 3 13:27:36 2021 +0000
```

thanks

**Comment by miromannino** [comment]
A very big typo error indeed! Thank you for doing that!
I just merged!
