### ISSUE TITLE
Remvove PR

### ISSUE THREAD

**Issue by eutudb23** [miromannino/Contributions-Importer-For-Github#43]
Hi mind removing my PR please, as I've wasn't paying attention and created against your work.
I mean, I'd want it removed since had some data which shouldn't be public :).

- PR to be removed: [PR 42](https://github.com/miromannino/Contributions-Importer-For-Github/pull/42)

You should be able to remove from the closed and if you have issue via the live bot from here by specifying the PR:

- https://support.github.com/request?q=I+need+to+delete+a+pull+request
![image](https://github.com/miromannino/Contributions-Importer-For-Github/assets/11492145/887c8aa6-2fb9-44d0-b618-bb9483219ceb)

Kind regards,
T

**Comment by miromannino** [comment]
Let me know if you also don't see it anymore

**Comment by eutudb23** [comment]
Yep, removed. Thank you sir!
Also I want to thank you for the content!
Have a nice rest of the day!
