### ISSUE TITLE
ModuleNotFoundError: No module named 'git_contributions_importer'

### ISSUE THREAD

**Issue by RicardoAugustoTulio** [miromannino/Contributions-Importer-For-Github#44]
```
...~/mock/Contributions-Importer-For-Github$ python3 run_script.py 
Traceback (most recent call last):
  File "...~/mock/Contributions-Importer-For-Github/run_script.py", line 3, in <module>
    from git_contributions_importer import *
ModuleNotFoundError: No module named 'git_contributions_importer'

```
run_script.py:

```
import git
from git_contributions_importer import *

repo = git.Repo("home/me/workspace/project")

mock_repo = git.Repo("/home/me/mock/mock-repo")

importer = Importer([repo], mock_repo)

importer.set_author(['personal_email@mail.com', 'bitbucket_email@mail.com.br'])
importer.import_repository()
```

**Comment by realanupreet** [comment]
I had the same issue, 

Replacing from `git_contributions_importer import *` with `from src import *` worked for me.

**Comment by RicardoAugustoTulio** [comment]
The script ran, but it did not import my contributions to the mock repository. Anyway, thank you very much for your help!

**Comment by RicardoAugustoTulio** [comment]
Sorry, 
In fact, it ran, but no commits are appearing in my contribution grid, can you tell me why this happens?

**Comment by realanupreet** [comment]
I hope you've added your work email on github aswell. As far as I know, it'll count in the comments that are made with your emails [that you've put on github].

**Comment by RicardoAugustoTulio** [comment]
it worked omg thanksssss <3<3<3
